# Site settings
title: Get Good Games
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the homepage for Get Good Games!
  We make games. Get Good.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getgoodgames.github.io/" # the base hostname & protocol for your site
twitter_username: getgoodgamesco
github_username:  GetGoodGames

# Build settings
markdown: kramdown
